// Generated by gencpp from file my_robot_msgs/LineRobotResult.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_MSGS_MESSAGE_LINEROBOTRESULT_H
#define MY_ROBOT_MSGS_MESSAGE_LINEROBOTRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_robot_msgs
{
template <class ContainerAllocator>
struct LineRobotResult_
{
  typedef LineRobotResult_<ContainerAllocator> Type;

  LineRobotResult_()
    : position(0)
    , message()  {
    }
  LineRobotResult_(const ContainerAllocator& _alloc)
    : position(0)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _position_type;
  _position_type position;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::my_robot_msgs::LineRobotResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_robot_msgs::LineRobotResult_<ContainerAllocator> const> ConstPtr;

}; // struct LineRobotResult_

typedef ::my_robot_msgs::LineRobotResult_<std::allocator<void> > LineRobotResult;

typedef boost::shared_ptr< ::my_robot_msgs::LineRobotResult > LineRobotResultPtr;
typedef boost::shared_ptr< ::my_robot_msgs::LineRobotResult const> LineRobotResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_robot_msgs::LineRobotResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_robot_msgs::LineRobotResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_robot_msgs::LineRobotResult_<ContainerAllocator1> & lhs, const ::my_robot_msgs::LineRobotResult_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_robot_msgs::LineRobotResult_<ContainerAllocator1> & lhs, const ::my_robot_msgs::LineRobotResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_robot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::LineRobotResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_msgs::LineRobotResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::LineRobotResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_msgs::LineRobotResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::LineRobotResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_msgs::LineRobotResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_robot_msgs::LineRobotResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "06665361780db4be123c7e09b6d2fd85";
  }

  static const char* value(const ::my_robot_msgs::LineRobotResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x06665361780db4beULL;
  static const uint64_t static_value2 = 0x123c7e09b6d2fd85ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_robot_msgs::LineRobotResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_robot_msgs/LineRobotResult";
  }

  static const char* value(const ::my_robot_msgs::LineRobotResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_robot_msgs::LineRobotResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result\n"
"int64 position\n"
"string message\n"
;
  }

  static const char* value(const ::my_robot_msgs::LineRobotResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_robot_msgs::LineRobotResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LineRobotResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_robot_msgs::LineRobotResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_robot_msgs::LineRobotResult_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    Printer<int64_t>::stream(s, indent + "  ", v.position);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROBOT_MSGS_MESSAGE_LINEROBOTRESULT_H
